### ISSUE TITLE
multigraph backup goes wrong

### ISSUE THREAD

**Issue by inertia** [everruler12/roam2github#1]
I am think you for your excellent work, it help me a lot. work so fine and new never got failed messages as before.

today i tried the new function to backup multigraph, and proceeded show this

`2021-02-04 10:05:56.034 R2G - Saving Markdown
2021-02-04 10:05:56.936 R2G Open graph F*********l
2021-02-04 10:05:56.936 R2G - (Wait 1 second)
2021-02-04 10:05:57.938 R2G - Navigating away to 404 (workaround)
2021-02-04 10:05:58.047 R2G - (Wait 1 second)
2021-02-04 10:05:59.048 R2G - Navigating to graph
2021-02-04 10:05:59.949 R2G - astrolabe spinning...
Error: The operation was canceled.`

just let you know.

**Comment by everruler12** [comment]
Known causes for timeout error `R2G astrolabe spinning... Error: The operation was canceled.`

  - Your `R2G_GRAPH` secret is incorrect.
  - Roam's servers happened to timeout.
  - You don't have permission to view that graph (in case of trying to backup someone else's graph)
    
To troubleshoot, try updating `R2G_GRAPH` for each graph one at a time (not the multi graph way), then re-run the Action's jobs. See if the error consistently happens for just the `F*********l` graph. Then you can try updating `R2G_GRAPH` with multiple graphs separated a different way: either by commas, or by new lines.

**Comment by inertia** [comment]
Thank you for your detail explanation.  Once backup a graph is  fine but two graphs at same time, it occured problem in Commit change step like this (sorry, i have no ideas about this)

`
INPUT_PUSH_OPTIONS: 
To https://github.com/***/roam-backup
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/***/roam-backup'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
`

**Comment by everruler12** [comment]
Since the Run Backup step completed, then my script seems to have worked. That error with the Commit Changes step usually happens when re-running a job after changes were already made. You can wait until the next scheduled run to see if it fails again.

**Comment by everruler12** [comment]
@inertia Any luck? If it's working, I'll close this issue

**Comment by inertia** [comment]
it works fine nnow. Thank you
